spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Asia/Tashkent

  mail:
    host: smtp.gmail.com
    port: 587
    username: hubProject1234@gmail.com
    password: exix cpos ndym fpkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      model: gpt-4o-mini

  data:
    redis:
      url: ${REDIS_URL}

server:
  port: ${PORT:8080}

app:
  docs-folder: "/app/app-knowledge/"
  base-folder: "/app/Agents/"
  logs-folder: "/app/logs/"
  user-register: "/app/user-registery"

app-security:
  token:
    access-exp: 6000
    refresh-exp: 86400
    secret: bu_secret_key_uzunligi_kamida_32_byte_boliswqewqewqewq