spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_controller
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: Asia/Tashkent
  mail:
    host: smtp.gmail.com
    port: 587
    username: hubProject1234@gmail.com
    password: exix cpos ndym fpkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
        model: gpt-4.0-mini

  spring:
    redis:
      host: localhost
      port: 6379
app:
  docs-folder: "/home/developer/MyApp/app-knowledge/"
  base-folder: "/home/developer/MyApp/Agents/"
  logs-folder: "/home/developer/MyApp/logs/"
  user-register: "/home/developer/MyApp/user-registery"

app-security:
  token:
    access-exp: 6000
    refresh-exp: 86400
    secret: bu_secret_key_uzunligi_kamida_32_byte_boliswqewqewqewq
