spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_controller}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Asia/Tashkent

  data:
    redis:
      host: ${REDISHOST:localhost}
      port: ${REDISPORT:6379}
      password: ${REDISPASSWORD:}
      username: ${REDISUSER:default}

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      base-url: https://api.groq.com/openai
      embedding:
        api-key: ${OPENAI_API_KEY}
        base-url: https://api.openai.com
        options:
          model: text-embedding-3-small
    chat:
      model: llama-3.3-70b-versatile

server:
  port: ${PORT:8080}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: onboarding@resend.dev

app:
  docs-folder: "/app/app-knowledge/"
  base-folder: "/app/Agents/"
  logs-folder: "/app/logs/"
  user-register: "/app/user-registery/users.log"

app-security:
  token:
    access-exp: 6000
    refresh-exp: 86400
    secret: bu_secret_key_uzunligi_kamida_32_byte_boliswqewqewqewq